server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USER}   # mets ça en variable d'env
    password: ${SMTP_PASS}   # mets ça en variable d'env
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  cors:
    allowed-origins:
      - http://localhost:4200
