spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  cors:
    allowed-origins:
      - https://thriving-pixie-ffb547.netlify.app
      - https://portfolio-fullstack-moise.onrender.com
      - https://sparkly-salamander-21f217.netlify.app
      - https://wonderful-bombolone-333898.netlify.app
      - https://ton-domaine.netlify.app
      - https://ton-domaine.vercel.app
